# Server config
server:
    host: 127.0.0.1
    port: 8080

# Database config
database:
    host: 127.0.0.1
    port: 5432
    username: postgres
    password: 1234

# Logging config
logging:
    level: debug

# Static files config
static:
    prefix: /public
    path: ./static
